// Bilingual site copy (TR + EN). One source of truth; components read the active
// language via useT() from LangProvider. Keep the two objects structurally identical.
export type Lang = "tr" | "en";

export const COPY = {
  tr: {
    nav: { how: "Nasıl?", features: "Özellikler", token: "Token", roadmap: "Yol Haritası", presale: "Ön Satış", play: "Oyna" },
    hero: {
      badge: "Telegram'da CANLI · TON üzerinde",
      title1: "Kurdu Besle.",
      title2: "TON'da $SANS Kazan.",
      desc: "Her dokunuşta kurdu beslersin, $SANS kazanırsın. Reklam izleyip 2× hız al, 10 seviye tırman, arkadaş davet et ve TON cüzdanını bağla — hepsi Telegram'da, bedava.",
      hl: "2× hız",
      playFree: "Ücretsiz Oyna",
      buy: "$SANS Al",
      t1: "🛡️ Sunucu doğrulamalı",
      t2: "💎 TON üzerinde",
      t3: "🎮 Bedava oyna",
      balanceLabel: "$SANS bakiye",
      boost: "⚡ 2× aktif",
    },
    how: {
      kicker: "60 saniyede başla",
      title: "Nasıl çalışır?",
      steps: [
        { title: "Telegram'da aç", desc: "Tek dokunuşla mini uygulamayı başlat — kurulum yok, kayıt yok. Saniyeler içinde oyundasın." },
        { title: "Kurdu besle", desc: "Her dokunuş kurdu et stokundan besler ve sana $SANS kazandırır. Et zamanla dolar." },
        { title: "Reklam izle → 2×", desc: "İstersen reklam izle: 30 dk 2× kazanç, bedava SANS, et dolumu ve ekstra çevirme." },
        { title: "Tırman & büyüt", desc: "10 seviye ve özel skinlerle yüksel, lider tablosuna çık, TON cüzdanını bağla." },
      ],
    },
    features: {
      kicker: "Tek uygulamada her şey",
      title: "Seni oyunda tutan tasarım",
      items: [
        { title: "10 seviye & skin", desc: "Yavru Kurt'tan Alfa'ya — toplam $SANS arttıkça her seviye yeni animasyonlu bir kurt skini açar." },
        { title: "Yükseltme & pasif gelir", desc: "Çoklu dokunuş, daha büyük et deposu, hızlı dolum ve sen yokken biriken pasif kazanç." },
        { title: "Ödüllü reklam & 2×", desc: "Reklam izle: 30 dk 2× kazanç, bedava SANS ya da anında et dolumu. Ya da reklamsız satın al." },
        { title: "Günlük seri & çark", desc: "Her gün gel: artan ödüller ve bir bedava şans çarkı. Gün kaçırırsan seri sıfırlanır." },
        { title: "Referans", desc: "Arkadaşını davet et — ikiniz de bonus kazanın, sürünüzü büyütün." },
        { title: "Canlı lider tablosu", desc: "Toplam kazanılan $SANS ile küresel sıralamada zirveye oyna." },
        { title: "TON cüzdan & ödeme", desc: "TON Connect ile cüzdanını bağla, reklamsız veya boost için zincir üstünde öde." },
        { title: "Sunucu doğrulamalı", desc: "Bakiye, enerji ve ödüller sunucuda hesaplanır — kurcalanamaz, hile yok." },
      ],
    },
    tokenomics: {
      kicker: "Arz Dağılımı",
      title: "Tokenomics",
      desc: "$SANS, TON üzerinde 1 milyar sabit arzlı bir jetton. Şeffaf dağılım, sahipleri sulandırmadan büyümeyi finanse eder; oyun büyüdükçe geri-alım ile SANS yakılır.",
      totalSupply: "Toplam Arz",
      segments: ["Ön Satış", "Likidite", "Oyun Ödülleri", "Pazarlama", "Ekip"],
      buybackTitle: "Deflasyonist geri-alım",
      buybackDesc: "Reklam gelirinin ve işlem ücretlerinin bir kısmı zincir üstü hazineye gider; periyodik olarak SANS geri alınıp yakılır — kullanım arttıkça arz azalır.",
    },
    roadmap: {
      kicker: "Yol Haritası",
      title: "Nereye gidiyoruz",
      labels: { done: "TAMAM", active: "AKTİF", next: "YAKINDA" },
      phases: [
        { tag: "Faz 01", title: "Oyun Canlı", status: "done", items: ["Telegram mini uygulama canlı", "Sunucu-otoriter motor", "10 seviye + skinler", "Reklam, yükseltme, referans, lider tablosu"] },
        { tag: "Faz 02", title: "TON & Ön Satış", status: "active", items: ["SANS jetton TON'da", "TON Connect cüzdan + ödeme", "1. Faz ön satış", "Monetag reklam geliri"] },
        { tag: "Faz 03", title: "Mainnet & Büyüme", status: "next", items: ["Mainnet jetton (sabit arz)", "TON'da DEX likidite", "Güvenlik denetimi", "Reklam ortaklıkları"] },
        { tag: "Faz 04", title: "Ölçeklenme", status: "next", items: ["Zincir üstü ödül / airdrop", "Stake & geri-alım otomasyonu", "CEX listeleri", "DAO yönetişimi"] },
      ],
    },
    presale: {
      badge: "1. Faz Ön Satış",
      title: "Listelenmeden $SANS kap",
      desc: "Oyunu erken destekle, en düşük fiyatı kilitle. Ön satış TON üzerinde gerçekleşir — katılmak ve zincir üstü alım açılınca haberdar olmak için Telegram duyuru kanalına gel.",
      perks: ["Erken fiyat", "erken alıcı bonusu", "Oyun içi sahip çarpanı & rozet", "TON mainnet dağıtımında öncelik"],
      token: "Token",
      priceLabel: "Ön satış fiyatı",
      listLabel: "Liste fiyatı",
      minLabel: "Minimum",
      supplyLabel: "Toplam arz",
      shareLabel: "Ön satış payı",
      cta: "Ön Satıştan Al",
      note: "Oyunda cüzdanını bağla → GRAM öde → SANS al",
    },
    trust: {
      kicker: "Neden SANS",
      badges: [
        { title: "Sunucu doğrulamalı", desc: "Bakiye, enerji ve ödüller sunucuda hesaplanır ve doğrulanır — istemci kurcalanamaz." },
        { title: "TON'da sabit arz", desc: "1 milyar $SANS jetton; sunucu-doğrulamalı, kötüye-kullanıma-dirençli ödüllü reklamlar." },
        { title: "Canlı & açık", desc: "Şu an Telegram'da oynanabilir — kurulum yok, kayıt yok. Almadan önce dene." },
      ],
      cta: "🐺 Telegram'da bedava oyna",
    },
    footer: {
      tagline: "Kurdu besle, TON'da $SANS kazan. Şeffaflık ve gerçek etkileşim üzerine kurulu bir Telegram tap-to-earn oyunu.",
      play: "Oyna",
      disclaimerTitle: "Sorumluluk reddi:",
      disclaimer: "SANS, SANS ekosistemi içinde kullanım için bir yardımcı token'dır (oyun ödülleri, reklam etkileşimi ve ekosistem erişimi). Bir menkul kıymet, yatırım sözleşmesi veya finansal araç değildir ve SANS tutmak herhangi bir varlıkta hisse/kâr payı/mülkiyet temsil etmez. Kripto para riski, anaparanın kaybı dahil, içerir. Bu sitedeki hiçbir şey finansal tavsiye değildir — ön satışa katılmadan önce kendi araştırmanı yap.",
    },
  },

  en: {
    nav: { how: "How?", features: "Features", token: "Token", roadmap: "Roadmap", presale: "Presale", play: "Play" },
    hero: {
      badge: "LIVE on Telegram · on TON",
      title1: "Feed the Wolf.",
      title2: "Earn $SANS on TON.",
      desc: "Every tap feeds the wolf and earns you $SANS. Watch an ad for a 2× boost, climb 10 tiers, invite friends and connect your TON wallet — all inside Telegram, free.",
      hl: "2× boost",
      playFree: "Play Free",
      buy: "Buy $SANS",
      t1: "🛡️ Server-verified",
      t2: "💎 On TON",
      t3: "🎮 Free to play",
      balanceLabel: "$SANS balance",
      boost: "⚡ 2× active",
    },
    how: {
      kicker: "Start in 60 seconds",
      title: "How it works",
      steps: [
        { title: "Open in Telegram", desc: "Launch the mini app in one tap — no install, no signup. You're playing in seconds." },
        { title: "Feed the wolf", desc: "Each tap feeds the wolf from your meat stock and earns you $SANS. Meat refills over time." },
        { title: "Watch an ad → 2×", desc: "Watch an optional ad: 30 min of 2× earnings, free SANS, a meat refill or an extra spin." },
        { title: "Climb & grow", desc: "Rise through 10 tiers with unique skins, hit the leaderboard, and connect your TON wallet." },
      ],
    },
    features: {
      kicker: "Everything in one app",
      title: "Built to keep you playing",
      items: [
        { title: "10 tiers & skins", desc: "From Pup to Alpha — every tier unlocks a new animated wolf skin as your total $SANS grows." },
        { title: "Upgrades & passive income", desc: "Multi-tap, bigger meat storage, faster refill and passive earnings that pile up while you're away." },
        { title: "Rewarded ads & 2×", desc: "Watch an ad for 30 min of 2× earnings, free SANS or an instant meat refill. Or buy ad-free." },
        { title: "Daily streak & spin", desc: "Come back daily for escalating rewards and a free lucky spin. Miss a day, the streak resets." },
        { title: "Referrals", desc: "Invite a friend — you both earn a bonus and grow your pack." },
        { title: "Live leaderboard", desc: "Play for the top of the global ranking by total $SANS earned." },
        { title: "TON wallet & payments", desc: "Connect with TON Connect and pay on-chain for ad-free or boosts." },
        { title: "Server-verified", desc: "Balance, energy and rewards are computed on the server — tamper-proof, no cheating." },
      ],
    },
    tokenomics: {
      kicker: "Supply Distribution",
      title: "Tokenomics",
      desc: "$SANS is a 1-billion fixed-supply jetton on TON. A transparent split funds growth without diluting holders; as the game grows, SANS is bought back and burned.",
      totalSupply: "Total Supply",
      segments: ["Presale", "Liquidity", "Game Rewards", "Marketing", "Team"],
      buybackTitle: "Deflationary buyback",
      buybackDesc: "A share of ad revenue and transaction fees goes to an on-chain treasury; SANS is periodically bought back and burned — supply shrinks as usage grows.",
    },
    roadmap: {
      kicker: "Roadmap",
      title: "Where we're headed",
      labels: { done: "DONE", active: "ACTIVE", next: "SOON" },
      phases: [
        { tag: "Phase 01", title: "Game Live", status: "done", items: ["Telegram mini app live", "Server-authoritative engine", "10 tiers + skins", "Ads, upgrades, referrals, leaderboard"] },
        { tag: "Phase 02", title: "TON & Presale", status: "active", items: ["SANS jetton on TON", "TON Connect wallet + payments", "Phase-1 presale", "Monetag ad revenue"] },
        { tag: "Phase 03", title: "Mainnet & Growth", status: "next", items: ["Mainnet jetton (fixed supply)", "DEX liquidity on TON", "Security audit", "Ad partnerships"] },
        { tag: "Phase 04", title: "Scaling", status: "next", items: ["On-chain rewards / airdrop", "Stake & buyback automation", "CEX listings", "DAO governance"] },
      ],
    },
    presale: {
      badge: "Phase-1 Presale",
      title: "Grab $SANS before listing",
      desc: "Back the game early and lock the lowest price. The presale runs on TON — join the Telegram announcement channel to take part and get notified when on-chain buying opens.",
      perks: ["Early price", "early-buyer bonus", "In-game holder multiplier & badge", "Priority in the TON mainnet distribution"],
      token: "Token",
      priceLabel: "Presale price",
      listLabel: "Listing price",
      minLabel: "Minimum",
      supplyLabel: "Total supply",
      shareLabel: "Presale share",
      cta: "Buy in Presale",
      note: "Connect your wallet in-game → pay GRAM → get SANS",
    },
    trust: {
      kicker: "Why SANS",
      badges: [
        { title: "Server-verified", desc: "Balance, energy and rewards are computed and verified on the server — the client can't be tampered with." },
        { title: "Fixed supply on TON", desc: "1 billion $SANS jetton; server-verified, abuse-resistant rewarded ads." },
        { title: "Live & open", desc: "Playable in Telegram right now — no install, no signup. Try before you buy." },
      ],
      cta: "🐺 Play free in Telegram",
    },
    footer: {
      tagline: "Feed the wolf, earn $SANS on TON. A Telegram tap-to-earn game built on transparency and real engagement.",
      play: "Play",
      disclaimerTitle: "Disclaimer:",
      disclaimer: "SANS is a utility token for use within the SANS ecosystem (game rewards, ad engagement and ecosystem access). It is not a security, investment contract or financial instrument, and holding SANS represents no share/dividend/ownership in any asset. Crypto carries risk, including loss of principal. Nothing on this site is financial advice — do your own research before joining the presale.",
    },
  },
} as const;
